In [29]:
import numpy as np
from sklearn import neighbors
from sklearn.neighbors import KNeighborsClassifier
knn = neighbors.KNeighborsClassifier(n_neighbors=2)
print(knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=2, p=2,
           weights='uniform')


In [8]:
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski', n_neighbors=2, p=2, weights='uniform')

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=2, p=2,
           weights='uniform')

In [21]:
knn.fit([[1],[2],[3],[4],[5],[6]], [0,0,0,1,1,1])
knn.predict([[1.5]])

array([0])

In [22]:
knn.predict([[37]])

array([1])

In [23]:
knn.predict([[3]])

array([0])

In [24]:
knn.predict_proba([[1.5]])

array([[1., 0.]])

In [25]:
knn.predict_proba([[37]])

array([[0., 1.]])

In [26]:
knn.predict_proba([[3.5]])

array([[0.5, 0.5]])

# Feature Engineering

In [27]:
import re
code_match = re.compile('<pre>(.*?)</pre>', re.MULTILINE | re.DOTALL)
link_match = re.compile('<a href="http://.*?".*?>(.*?)</a>', re.MULTILINE | re.DOTALL)
tag_match = re.compile('<[^>]*>', re.MULTILINE | re.DOTALL)


def extract_features_from_body(s):
    link_count_in_code = 0
    #count links in code to later subtract them
    for match_str in code_match.findall(s):
        link_count_in_code += len(link_match.findall(match_str))
    return len(link_match.findall(s)) - link_count_in_code

# Training the classifier

In [40]:
def fetch_posts():        
    for line in open("data.tsv", "r"):            
        post_id, text = line.split("\t")            
        yield post_id, text.strip()

all_answers = [q for q, v in meta.items() if v['ParentId'] !=-1]
Y = np.asarray([meta[answerId]['score']>0 for answerId in all_answers])

X = np.asarray([extract_features_from_body(text) for post_id, text in 
                fetch_posts() if post_id in all_answers])
knn = neighbors.KNeighborsClassifier()
knn.fit(X,y)

NameError: name 'meta' is not defined

# Could not continue. Data is too large for small harddrive. >23 gig.